### PR TITLE
Make sure matching multiline decorators with dots in the content don'…

### PR DESCRIPTION
**Pull request by therealburningman**
…t break the matching.

### CODE REVIEW

**Comment by mysim1** [comment]
solving: https://github.com/esdoc/esdoc-plugins/issues/36

**Comment by h13i32maru** [comment]
I can not have reproduce after I merged https://github.com/esdoc/esdoc/pull/472

**Comment by mysim1** [comment]
Thank you for merging my changes @h13i32maru 
This PR solves complex arguments in decorates, where the PR in the main project was just matching multiline arguments. Let me show you:
http://rubular.com/r/6UdWsNAQS1

You can see that the second decorator fails. This PR is intended to solve those complex argument. Do you need more information to replay this? LMK.

Summary:
multiline fix (in esdoc) complex argument fix (in esdoc-plugins)

**Comment by mysim1** [comment]
Additional note: The DocBuilder.js @ line 701 (splitting operation) will fail when complex decorators are involved. No clue why, because no time to dig in. My fix for now:
```
//TODO: when not split by ':' prevent breaking. Assuming this has to do with decorators. No clue what this does
        if (tmp.length!=2) {
          return `${v}: null`;
        }
```

**Comment by h13i32maru** [comment]
This changing breaks the behavior.
Please check https://github.com/esdoc/esdoc-plugins/commit/16560ff608947d1f8bee8123edf57f00ffa9e5c2

```javascript
'Foo#bar'.match(/(.*)[.#](.*)$/)
// => ["Foo#bar", "Foo", "bar", index: 0, input: "Foo#bar"]

'Foo#bar'.match(/(.*)[.#](?=.*\()(.*)$/)
// => null
```

**Pull request closed without merging**
