### PR TITLE
Much improved type reconstruction from Flow annotations.

### PR DESCRIPTION
**Pull request by samskivert**
- includes generic parameters: Foo<Bar, Baz>
- handles tuple types: [string, number]
- handles union types: string | void
- handles nullable types: ?string

### CODE REVIEW

**Comment by arabold** [comment]
Thanks for this PR. I've tested it locally with our environment and it works well. Hope this gets merged soon!

**Comment by h13i32maru** [comment]
Thanks! And sorry for the late reply.
It looks good to me. I'd like to merge, so please add a test code.

**Comment by samskivert** [comment]
Added the tests.

**Comment by Xal3ph** [comment]
This would fix so much for me - please fix this soon.

**Comment by samskivert** [comment]
I added tests, so in theory it's just waiting to be pushed.

I've actually made other improvements in a forked copy so I'll see about getting those into another PR.

**Comment by samskivert** [comment]
I just added them here. It's all work I did a while ago and which we've used extensively on a massive code base, so I'm pretty confident that this is all a strict improvement over what used to be.

**Pull request merged**
