### PR TITLE
esdoc-lint-plugin crash in case of arrow function bad declaration

### PR DESCRIPTION
**Pull request by paztis**
fix for defect https://github.com/esdoc/esdoc/issues/403 (created in esdoc repository instead of esdoc-plugins)

### CODE REVIEW

**Comment by pixelass** [comment]
Tested locally:

The error is more helpful than in the issue linked above.

Tested locally 

Before patch:

screen shot 2018-01-24 at 17 57 43

After patch:

screen shot 2018-01-24 at 17 59 15

**Comment by Trigalti** [comment]
Also tested this locally:
Before patching;
`TypeError: Cannot read property 'length' of undefined
    at Plugin._formatResult (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc-lint-plugin/src/Plugin.js:140:65)
    at Plugin.onPublish (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc-lint-plugin/src/Plugin.js:33:26)
    at Plugin._execHandler (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/Plugin/Plugin.js:55:26)
    at Plugin.onPublish (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/Plugin/Plugin.js:154:10)
    at Function._publish (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/ESDoc.js:354:24)
    at Function.generate (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/ESDoc.js:149:10)
    at ESDocCLI.exec (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/ESDocCLI.js:71:23)
    at Object.<anonymous> (/home/vagrant/workspace/adyen-es6-sdk/node_modules/esdoc/out/src/ESDocCLI.js:182:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)`

After patching:
`
warning: signature mismatch: submitPaymentForm src/payment-methods/actions.js#88
88| export const submitPaymentForm = (pDelaySubmit, e) => {
`

**Comment by pixelass** [comment]
I just wanted to note that this patch is essential to esdoc.

There is no reason not to merge it immediately. Honestly, without it we are just wasting precious time.

**Comment by pixelass** [comment]
In my case, this was an error:

Without this patch I would have never found it:

(`invalid`=> `props.invalid`)  
(`missing`=> `props.missing`)  
(`type`=> `props.type`)  

**WRONG**

```jsx
/**
 * Renders a warning containing useful information about the error that
 * caused the warning.
 * In general, it tells you what is wrong and what the correct usage
 * would look like. This is typically a text telling you that while 
 * you used component "A" only component "B" or "C" are allowed.
 * 
 * @private
 * @param {props} props
 *   The properties
 * @param {RectElement[]} props.not
 *   A list of components that are "not" allowed
 * @param {RectElement[]} props.only
 *   A list of "only" those components that are allowed
 * @param {Boolean} invalid
 *   Set this parameter if the warning is about invalid content
 * @param {Boolean} missing
 *   Set this parameter if the warning is about missing content
 * @param {String} type
 *   The type that was used and caused this warning
 */
```

**CORRECT**

```jsx
/**
 * Renders a warning containing useful information about the error that
 * caused the warning.
 * In general, it tells you what is wrong and what the correct usage
 * would look like. This is typically a text telling you that while 
 * you used component "A" only component "B" or "C" are allowed.
 * 
 * @private
 * @param {props} props
 *   The properties
 * @param {RectElement[]} props.not
 *   A list of components that are "not" allowed
 * @param {RectElement[]} props.only
 *   A list of "only" those components that are allowed
 * @param {Boolean} props.invalid
 *   Set this parameter if the warning is about invalid content
 * @param {Boolean} props.missing
 *   Set this parameter if the warning is about missing content
 * @param {String} props.type
 *   The type that was used and caused this warning
 */
```

**Comment by scottbasgaard** [comment]
Any reason why this can't go in?

**Comment by pixelass** [comment]
@scottbasgaard The maintainer has been very quiet for the past few months.  (last commit in this repo Nov 2017).

Let's hope everything is OK.

**Comment by scottbasgaard** [comment]
@pixelass :( didn't catch that and good to know. Hope everything is okay as well and love this tool!

**Pull request merged**
